// Generated by CoffeeScript 1.12.4
var fs, ignored, isType, path, transformFiles, transformModule;

isType = require("isType");

path = require("path");

fs = require("fsx");

transformFiles = require("./transformFiles");

ignored = require("./ignored");

exports.coffee = function(options) {
  var makePromise, modNames;
  modNames = options._;
  if (!modNames.length) {
    return transformModule(".", options);
  }
  makePromise = options.serial ? Promise.chain : Promise.all;
  return makePromise(modNames, function(modName) {
    return transformModule(modName, options);
  });
};

transformModule = function(modName, options) {
  var mod;
  mod = lotus.modules.load(modName);
  return mod.load(["config"]).then(function() {
    var pattern;
    if (mod.src == null) {
      mod.src = "src";
    }
    if (mod.dest == null) {
      mod.dest = "js";
    }
    if (mod.dest) {
      if (options.refresh) {
        fs.removeDir(mod.dest);
      }
      fs.writeDir(mod.dest);
    }
    pattern = path.relative(mod.path, mod.src + "/**/*");
    return mod.crawl(pattern, {
      ignore: ignored(options.ignore)
    }).then(function(files) {
      return transformFiles(files, options);
    });
  });
};
