// Generated by CoffeeScript 1.12.7
module.exports = {
  loadCommands: function() {
    return require("./cli");
  },
  initModule: function() {
    return require("./initModule");
  },
  globalDependencies: ["lotus-watch"]
};
