// Generated by CoffeeScript 1.12.4
var emptyFunction, fs, path, rimraf, transformFiles;

emptyFunction = require("emptyFunction");

rimraf = require("rimraf");

path = require("path");

fs = require("fsx");

transformFiles = require("./transformFiles");

module.exports = function(mod) {
  return mod.load("config").then(function() {
    var ignored, pattern, watcher;
    if (mod.src == null) {
      mod.src = "src";
    }
    if (mod.dest == null) {
      mod.dest = "js";
    }
    fs.writeDir(mod.dest);
    if (!fs.isDir(mod.src)) {
      log.warn("'mod.src' must be a directory:\n  " + mod.src);
      return null;
    }
    pattern = path.join(mod.src, "**", "*.coffee");
    ignored = "(.git|node_modules|__tests__|__mocks__)";
    watcher = mod.watch(pattern, {
      ignored: path.join("**", ignored, "**")
    });
    watcher.on("add", function(file) {
      var green;
      green = log.color.green;
      log.it("File added: " + (green(lotus.relative(file.path))));
      return transformFiles([file]);
    });
    watcher.on("change", function(file) {
      return transformFiles([file]);
    });
    watcher.on("unlink", function(file) {
      if (file.dest) {
        rimraf.sync(file.dest);
      }
      if (file.mapDest) {
        return rimraf.sync(file.mapDest);
      }
    });
    return watcher;
  });
};
