// Generated by CoffeeScript 1.12.4
var emptyFunction, fs, ignored, path, transformFiles;

emptyFunction = require("emptyFunction");

path = require("path");

fs = require("fsx");

transformFiles = require("./transformFiles");

ignored = require("./ignored");

module.exports = function(mod) {
  return mod.load("config").then(function() {
    var pattern, watcher;
    if (mod.src == null) {
      mod.src = "src";
    }
    fs.writeDir(mod.dest != null ? mod.dest : mod.dest = "js");
    pattern = path.relative(mod.path, mod.src + "/**/*");
    watcher = mod.watch(pattern, {
      ignore: ignored()
    });
    watcher.on("add", function(file) {
      var green;
      green = log.color.green;
      log.it("File added: " + (green(lotus.relative(file.path))));
      return transformFiles([file]);
    });
    watcher.on("change", function(file) {
      return transformFiles([file]);
    });
    watcher.on("unlink", function(file) {
      if (file.dest) {
        fs.removeFile(file.dest);
      }
      if (file.mapDest) {
        return fs.removeFile(file.mapDest);
      }
    });
    return watcher;
  });
};
