// Generated by CoffeeScript 1.12.7
var buildPath, buildVersions, createTransformer, findDependency, loadSpecific, semver, transformers, versions;

findDependency = require("find-dependency");

semver = require("semver");

createTransformer = require("./createTransformer");

versions = [];

transformers = Object.create(null);

if (buildPath = findDependency("coffee-build")) {
  buildVersions = require(buildPath + "/versions");
}

module.exports = function(version) {
  var range;
  if (semver.valid(version)) {
    return transformers[version] || loadSpecific(version);
  }
  if (semver.validRange(version)) {
    range = version;
    version = semver.maxSatisfying(versions, range);
    if (version) {
      return transformers[version];
    }
    version = semver.maxSatisfying(buildVersions, range);
    if (version) {
      return loadSpecific(version);
    }
  }
  throw Error("Invalid coffee-script version: '" + version + "'");
};

loadSpecific = function(version) {
  var coffee, transformer;
  coffee = require(buildPath + "/versions/" + version);
  versions.push(version);
  transformers[version] = transformer = createTransformer(coffee);
  return transformer;
};
