// Generated by CoffeeScript 1.12.7
var buildPath, buildVersions, createTransformer, findDependency, isObject, loadSpecific, semver, transformers, versions;

findDependency = require("find-dependency");

isObject = require("isObject");

semver = require("semver");

createTransformer = require("./createTransformer");

versions = [];

transformers = Object.create(null);

if (buildPath = findDependency("coffee-build")) {
  buildVersions = require(buildPath + "/versions");
}

module.exports = function(version) {
  var dep, range;
  if (isObject(version)) {
    dep = version;
    version = dep.version;
  }
  if (semver.valid(version)) {
    return transformers[version] || loadSpecific(version, dep != null ? dep.path : void 0);
  }
  if (semver.validRange(version)) {
    range = version;
    version = semver.maxSatisfying(versions, range);
    if (version) {
      return transformers[version];
    }
    version = semver.maxSatisfying(buildVersions, range);
    if (version) {
      return loadSpecific(version);
    }
  }
  throw Error("Invalid coffee-script version: '" + version + "'");
};

loadSpecific = function(version, dir) {
  var coffee, transformer;
  if (dir == null) {
    dir = buildPath + "/versions/" + version;
  }
  coffee = require(dir);
  versions.push(version);
  transformers[version] = transformer = createTransformer(coffee);
  return transformer;
};
