// Generated by CoffeeScript 1.12.7
var fs, parseDependencies, parseScripts, readJSON, resolveDependency, scriptRE;

fs = require("fsx");

scriptRE = /^coffee-build -v ([^\s]+)/;

module.exports = function(mod) {
  return parseDependencies(mod) || parseScripts(mod.config.scripts) || "1.12.x";
};

parseDependencies = function(mod) {
  var deps;
  if (deps = mod.config.devDependencies) {
    return resolveDependency("coffee-script", deps, mod) || resolveDependency("coffeescript", deps, mod);
  }
};

resolveDependency = function(name, deps, mod) {
  var dir;
  if (deps.hasOwnProperty(name)) {
    dir = fs.readLinks(mod.path + "/node_modules/" + name);
    if (fs.isDir(dir)) {
      return {
        path: dir,
        version: readJSON(dir + "/package.json").version
      };
    }
  }
};

parseScripts = function(scripts) {
  var match;
  if (match = scripts && scriptRE.exec(scripts.build)) {
    return match[1];
  }
};

readJSON = function(path) {
  return JSON.parse(fs.readFile(path));
};
